### PR TITLE
feat: search for similar urls in network sitemap

### LINKED ISSUE #22: [Task]: Redirects between the Shimmer and Mainnet version of the wiki often return a 404 error
The network/version switcher doesnt know which urls are available in the other versions, and if the URL doesnt exist in the other version, the user lands on a 404. Im thinking we could use the sitemaps to know what is the first dest url that is available, https://wiki.iota.org/sitemap.xml, https://wiki.iota.org/shimmer/sitemap.xml
https://github.com/iota-wiki/iota-wiki/issues/781

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Update network switcher component to find in the network sitemap for a similar url or a fallback. In case there aren't any, then redirect to a `/404`.

## Links to any relevant issues

Fixes #22 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
Seems to work, but, why redirect to the landing if there isn't a matching route? The task issue says to redirect to the 404, which I also think it makes more sense

**Comment by begonaalvarezd** [comment]
> Seems to work, but, why redirect to the landing if there isn't a matching route? The task issue says to redirect to the 404, which I also think it makes more sense

Yeah it might make more sense indeed, lets define a fallback route string (instead of magic strings) and redirect to the fallback which is the `/404` page within each version

**Comment by VmMad** [comment]
> > Seems to work, but, why redirect to the landing if there isn't a matching route? The task issue says to redirect to the 404, which I also think it makes more sense
> 
> Yeah it might make more sense indeed, lets define a fallback route string (instead of magic strings) and redirect to the fallback which is the `/404` page within each version

As a user I would prefer to be redirected in the landing instead of a 404 but that's okay, just an opinion.

**Review by marc2332 — APPROVED** [review]

**Comment by begonaalvarezd** [comment]
Closing PR to open in original repository

**Pull request closed without merging**
